#!/bin/bash

#1 Verifica si se proporcionó un directorio como argumento
if [ -z "$1" ]; then
  echo "Por favor, proporciona el directorio como argumento."
  exit 1
fi

#2 Encuentra el archivo más grande en el directorio especificado
archivo_mas_grande=$(find "$1" -type f -exec du -b {} + | sort -n -r | head -n 1)

#3 Muestra el archivo más grande
echo "El archivo más grande es:"
echo "$archivo_mas_grande"

# RECORDAR! Cuando nos de la opción para proporcionar el argumento debemos escribir bien la ruta exactamente como es sino nos dirá que el directorio no existe...
# RECORDAR! El directorio en el que queremos encontrar el archivo mas grande no puede estar en el mismo directorio que el archivo.sh... 
# Yo lo ejecuto de esta manera, ./namearchivo.sh \ruta\del\directorio 

Listo! 😁
